framework:
    default_locale: '%app.default_locale%'
    enabled_locales: '%app.supported_locales%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - de
            - en
        providers:
