framework:
    default_locale: de
    enabled_locales: ['de', 'en']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - de
            - en
        providers:
